version: "3"
services:
  app-client:
    container_name: property-manager-client
    build: ./app-client
    environment:
      - NODE_ENV=development
    volumes:
      - ./app-client:/usr/src/app
      - /usr/src/app/node_modules # This will mount the node_modules directory to the host machine using the buildtime directory.
    ports:
      - "3000:3000"
    networks:
      - app-network

  app-server:
    container_name: property-manager-server
    build: ./app-server
    environment:
      - NODE_ENV=development
    volumes:
      - ./app-server:/usr/src/app
      - /usr/src/app/node_modules # This will mount the node_modules directory to the host machine using the buildtime directory.
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - app-network
      - api-network

  mongodb:
    container_name: property-manager-mongodb
    image: mongo
    volumes:
      - ./mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

  nginx:
    container_name: property-manager-proxy
    build: ./nginx
    volumes:
      - ./nginx/ssl:/etc/ssl
    ports:
      - 8000:8000
    depends_on:
      - app-client 
      - app-server 
    networks:
      - app-network

  redis:
    container_name: service-rsa-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./service-rsa-redis/data:/data
    networks:
      - api-network

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge
