version: "3"
services:
  app-client:
    container_name: property-manager-client
    build: ./app-client
    environment:
      - NODE_ENV=development
    volumes:
      - ./app-client:/usr/src/app
    ports:
      - "3000:3000"
      - 35729:35729
    networks:
      - app-network

  app-server:
    container_name: property-manager-server
    build: ./app-server
    environment:
      - NODE_ENV=development
    volumes:
      - ./app-server:/usr/src/app
      - /usr/src/app/node_modules # This will mount the node_modules directory to the host machine using the buildtime directory.
    ports:
      - "8080:8080"
    networks:
      - app-network
      - api-network

  nginx:
    container_name: property-manager-proxy
    build: ./nginx
    volumes:
      - ./nginx/ssl:/etc/ssl
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app-client 
      - app-server 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  api-network:
    driver: bridge
